application: sc-cheese
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

libraries:
- name: django
  version: latest

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
